
import type { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Cosmic Voyager Tee',
    price: 29.99,
    imageUrl: 'https://picsum.photos/id/101/800/800',
    description: 'Explore the universe with this stunning cosmic design. Made from 100% premium cotton for ultimate comfort on your interstellar journeys.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Deep Space Black', 'Galaxy Purple', 'Stardust White'],
  },
  {
    id: 2,
    name: 'Retro Wave Tee',
    price: 24.99,
    imageUrl: 'https://picsum.photos/id/201/800/800',
    description: 'Ride the synthwave with this vibrant retro design. Perfect for late-night drives and dreaming of the 80s. A soft blend of cotton and polyester.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sunset Pink', 'Neon Blue', '8-Bit Black'],
  },
  {
    id: 3,
    name: 'Minimalist Mountain Tee',
    price: 27.99,
    imageUrl: 'https://picsum.photos/id/301/800/800',
    description: 'For the modern adventurer. This clean, minimalist mountain range design is printed on an eco-friendly, tri-blend fabric.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Heather Gray', 'Forest Green', 'Stone Blue'],
  },
  {
    id: 4,
    name: 'Abstract Geometry Tee',
    price: 32.99,
    imageUrl: 'https://picsum.photos/id/402/800/800',
    description: 'A wearable piece of art. This abstract geometric pattern is bold, unique, and sure to turn heads. Made with heavyweight combed cotton.',
    sizes: ['M', 'L', 'XL'],
    colors: ['Monochrome', 'Primary Colors', 'Pastel Hues'],
  },
    {
    id: 5,
    name: 'Ocean Depths Tee',
    price: 26.99,
    imageUrl: 'https://picsum.photos/id/503/800/800',
    description: 'Dive deep into style with this mesmerizing oceanic design. Features bioluminescent creatures on a deep navy background. 100% ring-spun cotton.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Midnight Blue', 'Seafoam Green', 'Coral Reef'],
  },
  {
    id: 6,
    name: 'Urban Jungle Tee',
    price: 28.99,
    imageUrl: 'https://picsum.photos/id/604/800/800',
    description: 'Navigate the concrete jungle in style. This tee features a striking graphic blending cityscapes with lush foliage. A durable and soft cotton blend.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: ['Concrete Gray', 'Moss Green', 'Skyline Blue'],
  },
  {
    id: 7,
    name: 'Cyberpunk Glitch Tee',
    price: 31.99,
    imageUrl: 'https://picsum.photos/id/705/800/800',
    description: 'A tribute to the high-tech, low-life future. The glitch art design is printed with high-density ink for a sharp, lasting look on premium cotton.',
    sizes: ['M', 'L', 'XL'],
    colors: ['Static Black', 'Glitch Magenta', 'Code Green'],
  },
  {
    id: 8,
    name: 'Zen Garden Tee',
    price: 25.99,
    imageUrl: 'https://picsum.photos/id/806/800/800',
    description: 'Find your inner peace with this calming Zen garden design. The soft-touch print on bamboo-derived fabric feels as serene as it looks.',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Sandstone', 'Pebble Gray', 'Water Blue'],
  },
];
